######################
# General parameters #
######################

z_score_cutoff: 1
min_colony_size_opacity: 12000  # too small a colony
iris_input_folder: './input/iris_files/' 
# variables contained in the iris filenames separated by '-'
column_names:
  - cond # cond: Combination of drugs adiminstred (antibiotics; inducers)
  - numb # numb: code for the concentration of drugs.  
         ## For example, SpectetIPTG-100101-5_1.JPG: number 100101: Spectomycin concentration 100; Tetracycline concentration 10, IPTG concentration 1
  - tail # tail: system_PLATEreplicate (third replicate in .docx)
         ## For example, SpectetIPTG-100101-5_1.JPG: tail 5_1: system 5, PLATEreplicate 1
control_gene_name: 'gfp'

