---
title: "TACTIC analysis script"
author: "Vallo Varik, Alessio Yang, Nicolai Karcher"
date: "2025-02-03"
output: html_document
---

# Get ready 


```{r setup, include=F}
`pacman::p_load(data.table, tidyverse, ggrepel, GGally, scales, ComplexHeatmap, limma, Biobase, cowplot, janitor)
options(datatable.print.nrows = 20)
source('./input/helper.R')

# ------------------------------  
# parameters to change
# ------------------------------  


z_score_cutoff <- 1

# IRIS files -------------------
iris_input_folder = './input/iris_files/' 

# variables contained in the iris filenames separated by '-'
# TODO: Make Alessio explain to you the format of the iris files:
# Iris output
# Profile: Colony growth
# Iris version: 0.9.7.8, revision id: 5121c26
# /Users/alessio/Documents/PhD/T5_Library/Solid screens/2024_Feb_29_T5-P1_TACTIC_Sen2_Eco9_Eco1/2024_Feb_29_T5P1condensed_TACTIC/SpectetampIPTG-10010501-4_2.JPG
# top left of the grid found at (0 , 33) # TODO: Am I right in asssuming that these top left/bottom right coordinates are simply 'sanity checks' to ensure IRIS found the grid properly?
# bottom right of the grid found at (4036 , 2663)
column_names = c("cond", "numb", "tail")
# numb: code for the concentration of drugs
# tail: system_PLATEreplicate (third replicate in .docx)

thr = 12000  # too small a colony

# Plate maps -------------------

# 1) create/adjust the 96w maps at './input/maps/library_plate_n.csv'

# 2) go from 96w to 384w to 1536
# TODO: ALessio will make sure to confirm that this works the way he thinks it works.
map96to384quadrants = registerQuadrants('384w', 
  plate_number = c(

    # first 384w plate
    1,  # 96w plate number in quadrant 1 
    2,  # 96w plate number in quadrant 2 
    3,  # ...
    2,  # 96w plate number in quadrant 4 

    # second 384w plate
    4,  # 96w plate number in quadrant 1 
    5,  # 96w plate number in quadrant 2
    6,  # ...
    6,  # 96w plate number in quadrant 4

    # third 384w plate
    1, 
    2, 
    3, 
    1,

    # fourth 384w plate
    4, 
    5, 
    6, 
    5
  ),
  bio_rep = c(
    1, 1, 1, 1,
    2, 2, 2, 2,
    1, 1, 1, 1,
    2, 2, 2, 2
  ),
  tech_rep = c(
    1, 1, 1, 2,
    1, 1, 1, 2,
    2, 3, 2, 3,
    2, 2, 3, 3
  )
)

map384to1536quadrants = registerQuadrants("1536w",
  plate_number = c(1,2,3,4) # TODO: TO be consistent with google scheme, make this work with letters
  # if needed, specify bio and tech reps; if not specified, default biorep=1, techrep=1)
  # TODO: Alessio: activate bio_rep and confirm that it works?
  # bio_rep = c(1, 2, 1, 2)
) # TODO: For safety reasons, remove biorep384, techrep384
`
```

```{r}
# TODO: Spec: Spectomycin, Tetracycling, Arabinose (inducer 1), IPTG (inducer 2, 2 concentrations)
folders = list.files(iris_input_folder, full.names=T)

iris = lapply(folders, loadIrisFiles) %>%
  setNames(gsub(paste0(iris_input_folder, '/'), '', folders)) %>%
  rbindlist(idcol='folder') %>%
  group_by(folder) %>%   # to annotate the same way in each folder
  mutate(plt1536 = match(file, unique(file))) %>%
  separate(file, column_names, sep='-') %>%
  mutate(tail = gsub('.JPG.iris', '', tail)) %>%
  separate(tail, c('system_num', 'biorep1536')) %>%
  rename(row1536=row, col1536=column) %>%
  left_join(fread('./input/maps/systems.csv', colClasses='character')) 

iris = left_join(map96to384quadrants, map384to1536quadrants, relationship = "many-to-many") %>%
  add384RowAndCol() %>%
  add1536RowAndCol() %>%
  right_join(iris) %>%
  as_tibble() %>%
  left_join(read96wMaps()) %>%
  mutate(
    colony_id  = interaction(plt1536, row1536, col1536),
    biorep_all = interaction(across(contains('biorep'))) %>% as.numeric() %>% str_pad(2, pad='0')) %>%
  setDT()
```


# QC and alternative analysis

```{r}
limma_results <- parallel::mclapply(unique(iris$folder), function(folder) {
  
  out_folder = paste0('./output/', folder)
  if(!dir.exists(out_folder)) dir.create(out_folder, recursive = T)

  fold = iris %>% filter(folder == {{folder}})
  # TODO: What is the difference between 'biorep_all' and 'biorep1536'?
  # biorep1536: 'real' biological replicate index (1, 2, 3)
  # biorep_all: also incoorporates plate information? 
  reps = c("biorep_all", "biorep1536")

  # TODO: Explain this to me:
  # fold %>% select(cond, plt1536) %>% table()
  #                 plt1536
  # cond                1    2    3    4    5    6    7    8    9   10   11   12
  #   Spectet        1536 1536    0    0    0    0    0    0    0    0    0    0
  #   SpectetAra        0    0 1536 1536    0    0    0    0    0    0    0    0
  #   SpectetAraIPTG    0    0    0    0 1536 1536 1536 1536    0    0    0    0
  #   SpectetIPTG       0    0    0    0    0    0    0    0 1536 1536 1536 1536



  # TODO:
  # print(fold) and look at it!

  # split to wide  ---------------------
  dat_wide = lapply(reps, function(x) {
    form = as.formula(paste('... ~', x))
    fold[[x]] = paste0('rep', fold[[x]])
    fold %>%
      # summarize gfp controls for there are hundreds of reps
      .[, .(opacity = median(opacity)), by=c('genename', 'cond', 'numb', x)] %>%
      dcast(form, value.var = 'opacity')
  }) %>% setNames(reps) 


  # plot-n-store the rep cor plots
  lapply(reps, function(x) {
    ggsave(paste0(out_folder, '/qc_', x, '_correlation.pdf'), 
      plotReplicateCorrelation(dat_wide[[x]]), h=12, w=12
    )
  })


  # plot-n-store the hierarchical clustering plots
  lapply(reps, function(x) {
    pdf(file=paste0(out_folder, '/qc_', x, '_clustering.pdf'), h=8, w=6)
    plt = plotHC(dat_wide[[x]])
    draw(plt)
    dev.off()
  })

  getResultsFromLinearModel(dat_wide[['biorep_all']], folder)
})
```



# Old analysis

```{r}
z_scoring_results <- map(unique(iris$folder), function(folder) {
  out_folder = paste0('./output/', folder)
  z = iris %>% filter(folder == {{ folder }})

  # separate conditions
  # TODO: Understand format of numb column: what does 1001001 mean?
  # This used to be but didn't retain anything for z1
  # z1 = subset(z, grepl('10010201', numb)) %>% rename(AraIPTG01 = opacity)
  z1 = subset(z, grepl("10010201", numb)) %>% rename(AraIPTG01 = opacity)
  z2 = subset(z, grepl("1001001", numb)) %>% select(IPTG01 = opacity)

  z3 = cbind(z1, z2) %>%
    # Remove strains where opacity is less than 12000 in the IPTG plates (too
    # small colonies to draw any conclusions)
    filter(IPTG01 > 12000) %>%
    mutate(
      Z.IPTG    = scale(IPTG01),
      Z.AraIPTG = scale(AraIPTG01),
      # TODO: We should probably incoorporate a parameter to designate whether its TIC or TAC
      ## in z diff: for blockers is the difference between AraIPTG-IPTG, for triggers is IPTG-AraIPTG
      Z.diff    = Z.IPTG - Z.AraIPTG
    )

  z4 = z3 %>%
    group_by(genename) %>%
    summarize(
      Z.mean = mean(Z.diff, na.rm = T),
      Z.sd   = sd(Z.diff, na.rm = T),
      lower  = Z.mean - Z.sd,
      upper  = Z.mean + Z.sd
    ) %>%
    # clean the names
    mutate(
      gene.name = sub("[.].*", "", genename),
      gene.name = sub("_", ".", gene.name),
      gene.name = sub("gp", "", gene.name)
    ) %>%
    # drop the ones with SD is 'NA' i.e. genenames with a single replicate
    filter(!is.na(Z.sd)) %>%
    # call hits and add color helpers for plotting
    mutate(
      isHit = Z.mean > z_score_cutoff,
      ## for blockers we use blue "#377eb8ff", for triggers green
      color = ifelse(isHit, "green4", "grey65")
    )

  z_score_plot <-(dotplot = z4 %>%
    {
      ggplot(., aes(
        x = gene.name, y = Z.mean, ymin = lower, ymax = upper,
        fill = color, label = gene.name
      )) +
        geom_pointrange(pch = 21) +
        scale_fill_identity() +
        labs(
          title = folder,
          x = "Genes",
          y = "Triggering score"
        ) +
        geom_text_repel(data = filter(., isHit)) +
        theme_bw() +
        theme(
          text = element_text(size = 10),
          axis.text.x = element_blank(),
          axis.ticks.x = element_blank(),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          axis.ticks.length = unit(.2, "cm")
        ) +
        geom_hline(yintercept = z_score_cutoff, linetype = "longdash", colour = "grey", size = 0.5)
    })

  ggsave(
    plot = z_score_plot,
    filename = str_c(out_folder, "/z_score_plot.pdf"),
    width = 9,
    height = 5
  )
  return(z4)
})
```
